#!/bin/bash
export GRAALVM_HOME=~/Library/Java/JavaVirtualMachines/graalvm-jdk-ea-25.0.0-ea.36/Contents/Home
export JAVA_HOME=~/Library/Java/JavaVirtualMachines/openjdk-ea-25+36-3489/Contents/Home

./gradlew clean nativeCompile
./build/native/nativeCompile/person-service -Xmx64m